data_list:
- '/stor/lep/workspace/AISbenchmark/Task1_data/Blood_raw.h5ad: single-cell RNA-seq
  data from human Blood.'
goal_description: Given this single-cell RNA-seq dataset from human Blood, annotate
  the cell type for each cell and return the h5ad file to me. Annotation must be done
  based on knowledge; external tools like CellTypist cannot be used
output_dir: /stor/lep/workspace/AISbenchmark/AutoBA/examples/Blood/output
