data_list:
- '/stor/lep/workspace/AISbenchmark/Task1_data/Bone_marrow_raw.h5ad: single-cell RNA-seq
  data from human Bone_marrow.'
goal_description: Given this single-cell RNA-seq dataset from human Bone_marrow, annotate
  the cell type for each cell and return the h5ad file to me. Annotation must be done
  based on knowledge; external tools like CellTypist cannot be used
output_dir: /stor/lep/workspace/AISbenchmark/AutoBA/examples/Bone_marrow/output
